name: Publish
on:
  workflow_dispatch:
    inputs:
      level:
        description: "Version level to bump"
        options:
          - major
          - minor
        type: choice
        default: minor
        required: true

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.calver.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cal Ver
        uses: speechifyinc/calver-action@v1.20230705.0
        id: calver
        with:
          level: ${{ github.event.inputs.level }}
          token: ${{ github.token }}

      - name: Update prod tag
        run: |
          git tag -f prod
          git push -f origin prod

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.calver.outputs.version }}

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          tag: ${{ needs.bump-version.outputs.version }}
          token: ${{ secrets.NPM_TOKEN }}
